name: XRT Build/Install Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: xcolinlocbld11-hosted-XRT-1
    container: artifactory.xilinx.com/xrt-build-docker-images-local/xrt-ubuntu1804:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      if: steps.cache-sha.outputs.cache-hit != 'true'
      run: |
        sudo apt update
        sudo src/runtime_src/tools/scripts/xrtdeps.sh
    - name: XRT Build
      run: cd build && chmod +x build.sh ; ./build.sh
    - name: Stash files
      uses: actions/upload-artifact@v2
      with:
        name: xrt-deb-ubuntu1804
        path: build/Release/xrt_*.deb

  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    needs: [build]
    steps:
      - name: Download XRT debs
        uses: actions/download-artifact@v2
        with:
          name: xrt-deb-ubuntu1804
      - name: Install xrt debs
        run: ls -al; sudo apt install -y ./*.deb
