name: XRT Build/Install Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted-docker-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      if: steps.cache-sha.outputs.cache-hit != 'true'
      run: |
        apt update
        src/runtime_src/tools/scripts/xrtdeps.sh

    - name: XRT Build
      run: cd build && chmod +x build.sh ; ./build.sh
    - name: Stash files
      uses: actions/upload-artifact@v2
      with:
        name: xrt-deb-ubuntu1604
        path: build/Release/xrt_*.deb

  install:
    runs-on: ubuntu-16.04
    needs: [build]
    steps:
      - name: Download XRT debs
        uses: actions/download-artifact@v2
        with:
          name: xrt-deb-ubuntu1604
      - name: Install xrt debs
        run: ls -al; sudo apt install -y ./*.deb
