name: XRT Build/Install Test CI

on:
  push:
    branches: [ master ]
  pull_request:	
    branches: [ master ]

jobs:
  build_centos74:
    runs-on: self-hosted-docker-centos74
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      if: steps.cache-sha.outputs.cache-hit != 'true'
      run: |
        sudo yum -y update
        sudo src/runtime_src/tools/scripts/xrtdeps.sh -docker
    - name: XRT Build
      run: cd build && chmod +x build.sh ; scl enable devtoolset-9 -- bash -c ./build.sh
    - name: Stash files
      uses: actions/upload-artifact@v2
      with:
        name: xrt-rpm-centos74
        path: build/Release/xrt_*-xrt.rpm
  uninstall_xrt:
    runs-on: self-hosted-centos74
    steps:
      - name: Uninstall xrt rpms
        run: ${{ secrets.SUDO }} yum remove -y xrt xrt-aws
  board_reset:
    runs-on: self-hosted-bf-runner
    steps:
      - name: Reset board
        run: ${{ secrets.BF_COMMAND }} --log-file /tmp/logs/board_reset.log xrt-reset -n ${{ secrets.BF_HOST }}
        shell: bash

  install_centos74:
    environment: Test
    runs-on: self-hosted-centos74
    needs: [build_centos74, uninstall_xrt]
    steps:
      - name: Download XRT rpms
        uses: actions/download-artifact@v2
        with:
          name: xrt-rpm-centos74
      - name: Install xrt rpms
        run: ls -al; ${{ secrets.SUDO }} yum install -y ./*.rpm
  board_test:
    environment: Test
    runs-on: self-hosted-bf-runner
    needs: [build_centos74, board_reset]
    steps:
      - name: Download XRT rpms
        uses: actions/download-artifact@v2
        with:
          name: xrt-rpm-centos74
      - name: Copy to bf 
        run: scp ./*.rpm ${{ secrets.BF_HOST }}:/home/${{ secrets.BF_USER }}/xrt-test-artifacts
      - name: Run on board
        run: ${{ secrets.BF_COMMAND }} --log-file /tmp/logs/test.OUTPUT xrt-test -n ${{ secrets.BF_HOST }} -p xilinx_u200_qdma_201910_1 -r 2021.1 -x /home/${{ secrets.BF_USER }}/xrt-test-artifacts/*-xrt.rpm --test_path ${{ secrets.BF_TESTS }} --timeout 2400 --results-path test.OUTPUT
        shell: bash

  hw_emulation_tests:
    runs-on: self-hosted-centos74
    needs: [install_centos74]
    steps:
      - name: Run HW Emulation tests
        run: |
          source /proj/xbuilds/2021.1_daily_latest/installs/lin64/Vitis/2021.1/settings64.sh
          source /opt/xilinx/xrt/setup.sh
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/proj/xbuilds/2021.1_daily_latest/installs/lin64/Vitis/2021.1/lib/lnx64.o/Default
          cd /scratch/tests/PCIE_VITIS_DSV_XRT_hw_emu_lin_lin_x86_20210128_035800_XRT_XILINX_U50_GEN3X16_XDMA_201920_3_MISC_lnx64/
          export XCL_EMULATION_MODE=hw_emu; ./host.exe -d acc -k kernel.xclbin
        shell: bash
